[[main]]
none = "none"

[[main]]
name = "Articles"
pageRef = "posts"
weight = 1

[[main]]
name = "Glossary"
pageRef = "glossary"
weight = 2

[[main]]
name = "About"
pageRef = "about"
weight = 3

[[footer]]
none = "none"
