colorScheme = "blowfish"
defaultAppearance = "dark"
autoSwitchAppearance = false
enableA11y = true
enableSearch = true
enableCodeCopy = false
replyByEmail = false
disableImageOptimization = false
disableImageOptimizationMD = false
disableTextInHeader = false
fingerprintAlgorithm = "sha512"
#giteaDefaultServer = "https://git.fsfe.org"
#forgejoDefaultServer = "https://v11.next.forgejo.org"
#firebase = { }
#fathomAnalytics = { }
#umamiAnalytics = { }
#selineAnalytics = { }
#buymeacoffee = { }
#verification = { }
#rssnext = { }
#advertisement = { }
logo = "/images/no-right-answers-logo-64.png"
secondaryLogo = "/images/no-right-answers-logo.png"
disableImageZoom = true
backgroundImageWidth = 1920
defaultBackgroundImage = "/images/bg.png"

[header]
layout = "fixed-fill"

[footer]
showMenu = false
showCopyright = true
showThemeAttribution = true
showAppearanceSwitcher = true
showScrollToTop = true

[homepage]
layout = "background"
homepageImage = "/images/bg.png"
showRecent = true
showRecentItems = "10"
showMoreLink = true
showMoreLinkDest = "/posts/"
cardView = true
cardViewScreenWidth = true
layoutBackgroundBlur = true
disableHeroImageFilter = false

[article]
showDate = true
showViews = false
showLikes = false
showDateOnlyInArticle = false
showDateUpdated = false
showAuthor = false
showHero = false
layoutBackgroundBlur = true
layoutBackgroundHeaderSpace = true
showBreadcrumbs = false
showDraftLabel = true
showEdit = false
editAppendPath = true
seriesOpened = false
showHeadingAnchors = true
showPagination = false
invertPagination = false
showReadingTime = false
showTableOfContents = false
showTaxonomies = true
showCategoryOnly = false
showAuthorsBadges = false
showWordCount = false
showZenMode = true
sharingLinks = ["bluesky", "mastodon" , "twitter", "linkedin"]

[list]
showHero = true
heroImage = "/images/bg.png"
heroStyle = "background"
layoutBackgroundBlur = true
layoutBackgroundHeaderSpace = false
showBreadcrumbs = false
showSummary = true
showViews = false
showLikes = false
showTableOfContents = false
showCards = true
orderByWeight = false
groupByYear = false
cardView = true
cardViewScreenWidth = false
constrainItemsWidth = false

[sitemap]
excludedKinds = [ "taxonomy", "term" ]

[taxonomy]
showTermCount = true
showHero = false
showBreadcrumbs = false
showViews = false
showLikes = false
showTableOfContents = false
cardView = false

[term]
showHero = false
showBreadcrumbs = false
showViews = false
showLikes = false
showTableOfContents = true
groupByYear = false
cardView = false
cardViewScreenWidth = false
